name: reviewdog
on:
  pull_request:
    paths:
    - '**.tf'
    - '**.tfvars'
    - '**.tfvars.json'
env:
  TERRAFORM_VERSION: "1.0.6"

jobs:

  tflint:
    name: runner / tflint
    runs-on: ubuntu-latest
    env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

    steps:
      - name: Test creds
        run: echo $AWS_ACCESS_KEY_ID

      - name: Clone repo
        uses: actions/checkout@master

      # Install latest Terraform manually as
      #  Docker-based GitHub Actions are
      #  slow due to lack of caching
      # Note: Terraform is not needed for tflint
      - name: Install Terraform
        run: |
          brew install tfenv
          tfenv install ${TERRAFORM_VERSION}

      # Run init to get module code to be able to use `--module`
      - name: Terraform init common
        run: |
          tfenv use ${TERRAFORM_VERSION}
          terraform init --upgrade

      # More complex example
      - name: tflint common
        uses: reviewdog/action-tflint@master
        with:
          github_token: ${{ secrets.github_token }}
          reporter: github-pr-review # Optional. Change reporter
          fail_on_error: true # Optional. Fail action if errors are found
          filter_mode: "added" # Optional. Check all files, not just the diff
          level: "warning"
          flags: "--module --loglevel=error" # Optional. Add custom tflint flags
